In [3]:
import numpy as np
import cv2

In [4]:
#some basic function of numpy
a = np.array([[1,2,3],[3,2,4],[4,5,6]])
b = np.zeros((8,6,3),dtype=np.uint8)
c = np.ones((8,8,3),dtype=np.uint8)
d = np.full((8,8,3),255,dtype=np.uint8)
e = np.identity(3)
f = np.eye(5,7,k = 0)
print(f)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]]


In [ ]:
#index and Assignment
img = np.zeros((512,512,3),dtype=np.uint8)
print(img[100,100])
count = 0
while count<200:
    img[count,100,2] = 255 #change different chanel number change RGB color
    count += 1
cv2.namedWindow("image",cv2.WINDOW_NORMAL)
cv2.imshow("image",img)
key = cv2.waitKey(0)
if(key == 'q'):
    exit()
cv2.destroyAllWindows()

[0 0 0]


In [ ]:
#how use roi
img1 = np.zeros((512,512,3),dtype=np.uint8)
roi = img1[100:500,100:600]
roi[:,:] = [255,0,0]#全部改为blue
roi[100:200,200:300] = [0,0,255]
cv2.imshow('roi',roi)
key = cv2.waitKey(0)
if(key == 'q'):
    exit()
cv2.destroyAllWindows()